version: '2'
services:
  elbazar-app:
    image: elbazar
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://elbazar-postgresql:5432/elbazar
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://elbazar-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://elbazar-elasticsearch:9200
    ports:
      - 8080:8080
  elbazar-postgresql:
    extends:
      file: postgresql.yml
      service: elbazar-postgresql
  elbazar-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elbazar-elasticsearch
